mount_smb: lots of improvements
1. Revamped how autossh is killed.  It was previously hanging around
   after the script exited.  More /etc/sudoers hacks are needed for
   this.  There's a new script, `removepidfile' that is used to kill
   autossh.  It needs to run via sudo, so it's (hopefully) locked down
   and is secure.

2. Changed the way the main body of the script executes.  Put
   everything inside:
      {
        # code here
	exit
      }
   which allows me to modify the script while it's running.  YAY!!
   This is a nice hack.

3. Make the script handle a bad SMB password.  That part was broken at
   some point.

diff --git a/mount_smb b/mount_smb
--- a/mount_smb
+++ b/mount_smb
@@ -40,8 +40,10 @@ function errordie {
     exit 1
 }
 
-[ "$(type -p autossh)" ] || errordie autossh: command not found
-[ "$(type -p ssh)" ] || errordie ssh: command not found
+autossh="$(type -p autossh)" || errordie autossh: command not found
+ssh="$(type -p ssh)" || errordie ssh: command not found
+removepidfile="$(type -p removepidfile)" ||
+    errordie removepidfile: command not found
 
 function usage {
     cat 1>&2 <<EOF
@@ -62,10 +64,11 @@ device to the remote machine.
 
 /etc/sudoers can be augmented, for easier operation.  Add these lines
 to the end with the "visudo" command:
-   \$USER ALL=(ALL) NOPASSWD: /sbin/ifconfig lo0 *
-   \$USER ALL=(ALL) NOPASSWD: /opt/local/bin/autossh
-   \$USER ALL=(ALL) NOPASSWD: /usr/bin/ssh
-where "\$USER" is replaced with the name of the user executing mount_smb.
+   Defaults        env_keep += "AUTOSSH_PIDFILE"
+   $USER ALL=(ALL) NOPASSWD: /sbin/ifconfig lo0 *
+   $USER ALL=(ALL) NOPASSWD: /opt/local/bin/autossh
+   $USER ALL=(ALL) NOPASSWD: /usr/bin/ssh
+   $USER ALL=(ALL) NOPASSWD: $removepidfile
 
 This script has been tested on Mac OS X 10.9.
 
@@ -170,10 +173,6 @@ EOF
 
 ###############################################################################
 
-mountpoints=
-
-ifconfig=/sbin/ifconfig
-
 function find_device {
     # Find the first unused lo0 IP address.
     local max=$(/sbin/ifconfig lo0 | \
@@ -184,14 +183,6 @@ function find_device {
     echo 127.0.0.$(( $max + 1 ))
 }
 
-if device=$(find_device); then
-    if [ ! "$device" ]; then
-	errordie Could not find device
-    fi
-else
-    errordie Could not find device
-fi
-
 function read_encoded_password {
     local pass
     [ "${EMACS-}" ] || stty -echo
@@ -200,16 +191,27 @@ function read_encoded_password {
     python -c "import sys, urllib as ul; print ul.quote(\"$pass\")"
 }
 
-# This file is removed by ssh once the control socket is shutdown
-socket=/tmp/smbtunnel$$
+function set_password {
+    echo "Enter your password for the SMB shares $smbhost:"
+    password="$(read_encoded_password)"
+    printf '\n'
+}
 
 function start_tunnel {
-    if ! sudo autossh -M 0 \
+    # Using -o ControlPersist=yes causes the autossh to not stick around,
+    # which is definitely not what we want, because the reconnect will not
+    # happen across sleeping the OS.  However, not using it also causes
+    # the autossh to stick around too long, after the ``-O exit'' is sent.
+    # I'd rather autossh's accumulate in the background than the reconnect
+    # not happen.
+    #
+    # To work around the above problem, we use AUTOSSH_PIDFILE and kill
+    # it manually when the script exits.
+    if ! sudo AUTOSSH_PIDFILE=$pidfile $autossh -M 0 \
 	 -L ${device}:139:${smbhost}:139 \
 	 -L ${device}:445:${smbhost}:445 \
 	 -F $sshconfig -i $sshid \
-	 -o ControlMaster=auto \
-	 -o ControlPersist=yes \
+	 -o ControlMaster=yes \
 	 -o ControlPath=$socket \
 	 -o ServerAliveInterval=10 \
 	 -o ServerAliveCountMax=3 \
@@ -244,41 +246,37 @@ function stop_tunnel_and_cleanup {
     if ! sudo $ifconfig lo0 ${device} -alias down; then
 	echo $ifconfig -alias down failed
     fi
+
     # do this last (so no need to error protect it)
     if [ -e $socket ]; then
-	echo Shutting down autossh...
-	sudo ssh $USER@$sshhost \
-	     -F $sshconfig -i $sshid -S $socket -O exit
+	sshargs="$USER@$sshhost -F $sshconfig -i $sshid -S $socket "
+	echo Shutting down ssh...
+	sudo $ssh $sshargs -O exit
+	echo Killing autossh
+	sudo $removepidfile $pidfile
     else
 	echo Warning: autossh socket does not exist, cannot shut it down
     fi
 }
 
-sudo $ifconfig lo0 ${device} alias up
-
-start_tunnel
-trap "stop_tunnel_and_cleanup" 0
-
-echo Waiting for tunnel to initialize on ${device}
-sleep 5
-[ -e $socket ] || errordie autossh did not create $socket file
-
-function mountit {
+function mount_shares {
     local mountpoint
-    
-    echo "Enter your password for the SMB shares $smbhost:"
-    pass="$(read_encoded_password)"
-    printf '\n'
 
+    set_password
+    
     for share in $shares; do
 	mountpoint="/Volumes/$smbhost-$share"
 	mountpoints="$mountpoints $mountpoint"
 
 	mkdir -p $mountpoint
 
-	/sbin/mount_smbfs \
-	    "//${workgroup};${remoteuser}:${pass}@${device}/${share}" \
-	    $mountpoint
+	while ! /sbin/mount_smbfs \
+		"//${workgroup};${remoteuser}:${password}@${device}/${share}" \
+		$mountpoint
+	do
+	    # Assume it failed because the password was incorrect
+	    set_password
+	done
 
 	# If a function named "mount_smb_post_mount" was defined in
 	# $HOME/.mount_smb (or possibly in $HOME/.bashrc), then call it.
@@ -295,14 +293,45 @@ function mountit {
     done
 }
 
-# Do this in a loop, in case the user types the password incorrectly.
-while ! mountit; do
-    :
-done
+###############################################################################
 
-cat <<EOF
+# We put the main body of code in a list {} so that if the script is
+# modified after it starts it won't cause problems.
+{
+    password=
+
+    mountpoints=
+
+    ifconfig=/sbin/ifconfig
+
+    # This file is removed by ssh once the control socket is shutdown
+    socket=/tmp/smbtunnel$$
+    pidfile=/tmp/autosshpid$$
+
+    if device=$(find_device); then
+	if [ ! "$device" ]; then
+	    errordie Could not find device
+	fi
+    else
+	errordie Could not find device
+    fi
+
+    sudo $ifconfig lo0 ${device} alias up
+
+    start_tunnel
+    trap "stop_tunnel_and_cleanup" 0
+
+    echo Waiting for tunnel to initialize on ${device}
+    sleep 5
+    [ -e $socket ] || errordie autossh did not create $socket file
+
+    mount_shares
+
+    cat <<EOF
 When you are done with the share, press ENTER and it will be unmounted
 EOF
-read foo
+    read foo
 
-# the cleanup is done in the trap handler
+    # the cleanup is done in the trap handler
+    exit
+}
