onall: tweak printing
Only print something for a host if the command produced output.

diff --git a/onall b/onall
--- a/onall
+++ b/onall
@@ -2,6 +2,8 @@
 # examples:
 # $ ./onall.sh -d bink -e '(layerpro|gremlin|git)' git pull -r
 
+prog="$(basename "$0")"
+
 usage="[-i] [-e regex] [-d directory] [-u user] command args...
 
 -i :: ignore errors
@@ -10,21 +12,16 @@ usage="[-i] [-e regex] [-d directory] [-u user] command args...
 -u :: execute as 'user'
 "
 
-set -eu
-set -o pipefail
-
-self="${BASH_SOURCE[0]}"
-SCRIPTDIR=$(cd "$(dirname "$self")" && pwd)
-argv0="$(basename "$self")"
+set -ueE -o pipefail
 
 function usage {
-    [ "${*-}" ] && echo "$argv0: Error: $*" 1>&2
-    echo "Usage: $argv0: $usage" 1>&2
+    [ "${*-}" ] && echo "$prog: Error: $*" 1>&2
+    echo "Usage: $prog: $usage" 1>&2
     exit 1
 }
 
 function errordie {
-    [ "${*-}" ] && echo "$argv0: Error: $*" 1>&2
+    [ "${*-}" ] && echo "$prog: Error: $*" 1>&2
     exit 1
 }
 
@@ -61,7 +58,7 @@ if [ "$except" ]; then
     tmp=
     for h in $hosts; do
 	if [[ $h =~ $except ]]; then
-	    echo Note: skip host $h
+	    echo "Note: skip host $h"
 	else
 	    tmp="$tmp $h"
 	fi
@@ -76,20 +73,35 @@ for ARG in "$@"; do
     QUOTE_ARGS="${QUOTE_ARGS} $ARG"
 done
 
+tempfile="/tmp/${prog}temp$$"
+rm -f "$tempfile"
+function exit_cleanup {
+    /bin/rm -f "$tempfile"
+}
+function err_report {
+    echo "Error on line $(caller)" 1>&2
+}
+trap err_report   ERR
+trap exit_cleanup EXIT
+
 {
     for h in $hosts; do
-	echo ""
-	echo ============= $h ========================================
-	echo ""
+        rm -f "$tempfile"
 	if [ "${SSH_IDENT-}" ]; then
 	    ssh="ssh -A -i .ssh/${SSH_IDENT}"
 	else
 	    ssh="ssh -A"
 	fi
 	if [ "$ignoreerrors" ]; then
-	    $ssh ${user}@$h "$cd${QUOTE_ARGS}" || true
+	    $ssh "${user}@$h" "$cd${QUOTE_ARGS}" || true >> "$tempfile"
 	else
-	    $ssh ${user}@$h "$cd${QUOTE_ARGS}"
+	    $ssh "${user}@$h" "$cd${QUOTE_ARGS}" >> "$tempfile"
 	fi
+
+        if [ -s "$tempfile" ]; then
+	    echo ""
+	    echo "============= $h ========================================"
+            cat "$tempfile"
+        fi
     done
 }
